name: Black Hat
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - id: changed
        uses: ashishkurmi/changed-files@main
        with:
          files: |
            infrastructure/**
            terraform/**
            
