name: 'Sample Workflow'
on:
  issue_comment:
    types: [created]
  pull_request_target:

jobs:
  sample-workflow:
    if: |
      github.repository_owner == 'ashishkurmi' &&
      (
        github.event_name == 'pull_request_target' ||
        (
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request &&
          startsWith(github.event.comment.body, '/sample workflow')
        )
      )
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello World"

      - name: Get PR Information
        id: pr-info
        run: |
          set -x
          PR_NUM=${{ github.event.number || github.event.issue.number }}
          echo "PR_INFO=$(gh -R ${{ github.repository }} pr view ${PR_NUM} --json headRepository,headRepositoryOwner,headRefName | jq -c)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          repository: '${{ fromJSON(steps.pr-info.outputs.PR_INFO).headRepositoryOwner.login }}/${{ fromJSON(steps.pr-info.outputs.PR_INFO).headRepository.name }}'
          ref: '${{ fromJSON(steps.pr-info.outputs.PR_INFO).headRefName }}'
