name: 'Sample Workflow'
on:
  issue_comment:
    types: [created]
  pull_request_target:

jobs:
  sample-workflow:
    if: |
      github.repository_owner == 'ashishkurmi' &&
      (
        github.event_name == 'pull_request_target' ||
        (
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request &&
          startsWith(github.event.comment.body, '/sample workflow')
        )
      )
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello World"
